# Site settings

author: Nicolas Centa
email: nicolas.centa@gmail.com
github_username:  HappyPeng2x
github_project: SumatoraDictionary

head-title: Sumatora Japanese Dictionary
title: Sumatora Japanese Dictionary

baseurl: ""    # the subpath of your site, "/blog"
url: ""


#
# Build settings
#

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

plugins: [jekyll-paginate]

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

